Fix: Handle self-signed certificates in Redis
electron/update.electronjs.org pull request #134
Opened 2023-05-18 14:24 UTC by felixrieseberg

I _believe_ that this fixes an issue with self-signed certificates.

```
2023-05-18T13:31:17.000000+00:00 app[redis-curly-70223]: Error accepting a client connection: (null)
2023-05-18T13:31:17.195403+00:00 app[web.1]: http://localhost:54531
2023-05-18T13:31:17.203319+00:00 app[web.1]: node:internal/process/promises:288
2023-05-18T13:31:17.203320+00:00 app[web.1]: triggerUncaughtException(err, true /* fromPromise */);
2023-05-18T13:31:17.203321+00:00 app[web.1]: ^
2023-05-18T13:31:17.203321+00:00 app[web.1]:
2023-05-18T13:31:17.203321+00:00 app[web.1]: Error: self-signed certificate in certificate chain
2023-05-18T13:31:17.203321+00:00 app[web.1]: at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
2023-05-18T13:31:17.203321+00:00 app[web.1]: at TLSSocket.emit (node:events:513:28)
2023-05-18T13:31:17.203322+00:00 app[web.1]: at TLSSocket._finishInit (node:_tls_wrap:959:8)
2023-05-18T13:31:17.203322+00:00 app[web.1]: at ssl.onhandshakedone (node:_tls_wrap:743:12)
2023-05-18T13:31:17.203322+00:00 app[web.1]: Emitted 'error' event on Commander instance at:
2023-05-18T13:31:17.203322+00:00 app[web.1]: at RedisSocket.<anonymous> (/app/node_modules/@redis/client/dist/lib/client/index.js:392:14)
2023-05-18T13:31:17.203323+00:00 app[web.1]: at RedisSocket.emit (node:events:513:28)
2023-05-18T13:31:17.203323+00:00 app[web.1]: at RedisSocket._RedisSocket_connect (/app/node_modules/@redis/client/dist/lib/client/socket.js:167:18)
2023-05-18T13:31:17.203323+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-05-18T13:31:17.203323+00:00 app[web.1]: at async getCache (/app/bin/update-server.js:40:3) {
2023-05-18T13:31:17.203324+00:00 app[web.1]: code: 'SELF_SIGNED_CERT_IN_CHAIN'
2023-05-18T13:31:17.203324+00:00 app[web.1]: }
2023-05-18T13:31:17.203324+00:00 app[web.1]:
2023-05-18T13:31:17.203324+00:00 app[web.1]: Node.js v18.16.0
2023-05-18T13:31:17.338354+00:00 heroku[web.1]: Process exited with status 1
2023-05-18T13:31:17.365145+00:00 heroku[web.1]: State changed from starting to crashed
```

2023-05-22 20:27 UTC, felixrieseberg commented
Update: This PR was successfully deployed to https://staging.update.electronjs.org and verified there ✅

2023-05-23 11:37 UTC, BlackHole1 requested changes

2023-05-23 11:37 UTC, BlackHole1 commented on README.md
> +2) Docker: Install and run Redis with `docker run -p 6379:6379 -it redis/redis-stack-server:latest`.
Perhaps is `redis`?

```suggestion
2) Docker: Install and run Redis with `docker run -p 6379:6379 -it redis:latest` .
```

2023-05-23 23:15 UTC, BlackHole1 approved these changes

2023-05-24 15:52 UTC, merged