Add support for ARM, update dependencies
electron/update.electronjs.org pull request #84
Opened 2020-11-19 20:59 UTC by felixrieseberg

This PR contains exactly what's in the title: I've added support for ARM on both Windows and macOS and updated a number of depenendencies.

I've also done some _very minor_ refactoring, most of which was required by `standard`.

2020-11-24 16:15 UTC, malept requested changes
I think `-arm` should be `-arm64` across the board, to be consistent with our usage of Node-style arch names.

2020-11-24 16:15 UTC, malept commented on index.js
> +    console.log(releases)
Should probably remove this before merging.
```suggestion
```

2020-11-24 16:15 UTC, malept commented on index.js
> +    console.log(latest)
More debug

```suggestion
```

2020-11-24 16:15 UTC, malept commented on index.js
> +    for (const key of [PLATFORM_ARCH.WIN_X64, PLATFORM_ARCH.WIN_IA32]) {
Should win-arm64 be included here?

2020-11-24 16:15 UTC, malept commented on index.js
> +}
Should win-arm64 be added here?

2020-12-09 17:26 UTC, malept requested changes
I think these should be the last changes and then we should be good to go.

2020-12-09 17:26 UTC, malept commented on index.js
> +  if (/win32-arm/.test(fileName)) return PLATFORM_ARCH.WIN_ARM64
```suggestion
  if (/win32-arm64/.test(fileName)) return PLATFORM_ARCH.WIN_ARM64
```

2020-12-09 17:26 UTC, malept commented on index.js
> +  )
```suggestion
  return !!(
    latest[PLATFORM_ARCH.DARWIN_X64] ||
    latest[PLATFORM_ARCH.DARWIN_ARM64] ||
    latest[PLATFORM_ARCH.WIN_X64] ||
    latest[PLATFORM_ARCH.WIN_IA32] ||
    latest[PLATFORM_ARCH.WIN_ARM64]
  )
```

2020-12-09 17:26 UTC, malept commented on index.js
> +        : 'No updates found (needs asset containing win32-{x64,ia32,arm} or .exe in public repository)'
```suggestion
        : 'No updates found (needs asset containing win32-{x64,ia32,arm64} or .exe in public repository)'
```

2020-12-11 20:00 UTC, malept approved these changes
In a follow-up PR, we should move to GitHub Actions.

:shipit:

2020-12-13 19:30 UTC, marcello3d commented
Will this work with a macOS universal app? E.g. both arm + x64 in one .zip?

2020-12-13 23:37 UTC, felixrieseberg commented
> Will this work with a macOS universal app? E.g. both arm + x64 in one .zip/.app?

Not right now, but a PR would be welcome!

2020-12-13 23:37 UTC, merged

2020-12-14 13:04 UTC, tazzben commented
Does someone know when this will be deployed to the server?